### ISSUE TITLE
Node Red crashing

### ISSUE THREAD

**Issue by ebnerjoh** [oe8chk/nodeBlSms#2]
```
26 Sep 01:19:15 - [red] Uncaught Exception:
26 Sep 01:19:15 - Error: getaddrinfo EAI_AGAIN api.blaulichtsms.net:443
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1


npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /usr/src/node-red/.npm/_logs/2019-09-25T23_19_15_723Z-debug.log

> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
```

I had blaulicht-sms integration running for a couple of months without issues but have disabled it several months ago. I have enabled again this sunday but I had now the second crash of Node Red.

**Comment by riederch** [comment]
Hi,
Sorry for my late answer, maybe it could be a timeout like described here:
https://stackoverflow.com/questions/40182121/error-getaddrinfo-eai-again
I will add a better exception handling as soon as possible

**Comment by riederch** [comment]
Hi,
If you run the install script of V0.1.4 the update will be installed.
If the error occurs again, there should appear such a message:
![grafik](https://user-images.githubusercontent.com/11293087/65911254-a7d37f00-e3cc-11e9-9de3-d56debcc6465.png)
